// 사용한 API : TMDB 현재 한국에서 상영 중인 영화 API
// API Document : https://developers.themoviedb.org/3/movies/get-now-playing
// Request : https://api.themoviedb.org/3/movie/now_playing?api_key=c4e59022826dc465ea5620d6adaa6813&language=ko&page=1&region=KR

// 아래는 Response Data
export const dummy = {
  dates: { maximum: "2022-09-19", minimum: "2022-08-02" },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/2RSirqZG949GuRwN38MYCIGG4Od.jpg",
      genre_ids: [53],
      id: 985939,
      original_language: "en",
      original_title: "Fall",
      overview:
        "내려갈 길이 끊겨버린 600미터 TV 타워 위에서  두 명의 친구가 살아남기 위해 펼치는 사상 최초의 고공 서바이벌",
      popularity: 6824.053,
      poster_path: "/1OdA3gOq8N5KWwXsZhYVHbeyx8l.jpg",
      release_date: "2022-08-11",
      title: "폴: 600미터",
      video: false,
      vote_average: 7.4,
      vote_count: 753,
    },
    {
      adult: false,
      backdrop_path: "/1n7ZGr6WeDOW4rFiQKmFel8baWH.jpg",
      genre_ids: [12, 18, 27],
      id: 760741,
      original_language: "en",
      original_title: "Beast",
      overview:
        "두 딸 ‘메어’, ‘노라’와 함께 시간을 보내기 위해 친구 ‘마틴’이 있는 남아프리카를 찾은 의사 ‘네이트’.  그러나 즐거운 여행도 잠시, 처참히 죽어 있는 마을 사람들을 목격한 이들은 곧이어 이 모든 상황을 벌인 사자에게 맹목적으로 쫓기기 시작한다.  무전조차 터지지 않는 고립된 지역에서 마을을 완전히 장악해버린 사자로부터 벗어나기 위해 서로 의지하며 고군분투하는데…",
      popularity: 4680.185,
      poster_path: "/xp6EOh0HEN4bx4ot8UfcYnUpT8U.jpg",
      release_date: "2022-08-11",
      title: "비스트",
      video: false,
      vote_average: 7.1,
      vote_count: 389,
    },
    {
      adult: false,
      backdrop_path: "/ugS5FVfCI3RV0ZwZtBV3HAV75OX.jpg",
      genre_ids: [16, 878, 28],
      id: 610150,
      original_language: "ja",
      original_title: "ドラゴンボール超 スーパーヒーロー",
      overview: "2018년에 개봉한 에 이은  시리즈의 두 번째 영화",
      popularity: 2976.814,
      poster_path: "/uohymzBVaIYjbnoQstbnlia6ZPJ.jpg",
      release_date: "2022-06-11",
      title: "드래곤볼 슈퍼: 슈퍼 히어로",
      video: false,
      vote_average: 8,
      vote_count: 1667,
    },
    {
      adult: false,
      backdrop_path: "/skL7c4ZhZqo1IFbMcHNrol4fvkc.jpg",
      genre_ids: [28, 80, 53],
      id: 921360,
      original_language: "en",
      original_title: "Wire Room",
      overview: "",
      popularity: 1981.35,
      poster_path: "/b9ykj4v8ykjRoGB7SpI1OuxblNU.jpg",
      release_date: "2022-09-02",
      title: "와이어 룸",
      video: false,
      vote_average: 7.2,
      vote_count: 65,
    },
    {
      adult: false,
      backdrop_path: "/qaTzVAW1u16WFNsepjCrilBuInc.jpg",
      genre_ids: [16, 28, 12],
      id: 539681,
      original_language: "en",
      original_title: "DC League of Super-Pets",
      overview:
        "악당 렉스 루터의 계략으로 위험에 빠진 슈퍼맨을 비롯한 저스티스 리그의 슈퍼 히어로들을 구하기 위해 슈퍼독 크립토와 슈퍼 펫 친구들이 벌이는 파워 댕댕 모험을 그린 이야기",
      popularity: 1635.032,
      poster_path: "/4L7hgezinra0QudLN8HPv8c3af1.jpg",
      release_date: "2022-07-27",
      title: "DC 리그 오브 슈퍼-펫",
      video: false,
      vote_average: 7.5,
      vote_count: 593,
    },
    {
      adult: false,
      backdrop_path: "/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg",
      genre_ids: [16, 12, 35, 14],
      id: 438148,
      original_language: "en",
      original_title: "Minions: The Rise of Gru",
      overview:
        "세계 최고의 슈퍼 악당을 꿈꾸는 미니보스 ‘그루’와 그를 따라다니는 미니언들. 어느 날 그루는 최고의 악당 조직 ‘빌런6’의 마법 스톤을 훔치는 데 성공하지만 뉴페이스 미니언 ‘오토’의 실수로 스톤을 잃어버리고 빌런6에게 납치까지 당한다. 미니보스를 구하기 위해 잃어버린 스톤을 되찾아야 하는 ‘오토’, 그리고 쿵푸를 마스터해야 하는 ‘케빈’, ‘스튜어트’, ‘밥’! 올 여름 극장가를 점령할 MCU(미니언즈 시네마틱 유니버스)가 돌아온다!",
      popularity: 1481.2,
      poster_path: "/1heBUD8o0sgdqLWyeXkylR2POKb.jpg",
      release_date: "2022-06-29",
      title: "미니언즈 2",
      video: false,
      vote_average: 7.6,
      vote_count: 1982,
    },
    {
      adult: false,
      backdrop_path: "/5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg",
      genre_ids: [27, 53],
      id: 760161,
      original_language: "en",
      original_title: "Orphan: First Kill",
      overview:
        "엄청난 비밀을 숨긴 사이코패스가 에스토니아의 정신병동을 탈출,\r 부유한 가족의 실종된 딸 ‘에스더’로 사칭해 미국에 온다.\r 재회의 기쁨도 잠시, 어딘지 낯선 딸의 정체를 눈치챈 엄마는\r 가족을 지키기 위해 에스더와 맞서는데...  누구도 상상 못한 충격적인 반전이 기다린다!",
      popularity: 1573.405,
      poster_path: "/vKIhsEVEtLTwTkmLSDNi230Zr3Q.jpg",
      release_date: "2022-07-27",
      title: "오펀: 천사의 탄생",
      video: false,
      vote_average: 7.1,
      vote_count: 622,
    },
    {
      adult: false,
      backdrop_path: "/AfvIjhDu9p64jKcmohS4hsPG95Q.jpg",
      genre_ids: [27, 53],
      id: 756999,
      original_language: "en",
      original_title: "The Black Phone",
      overview:
        "사라진 아이들, 고장 난 전화기, 죽은 친구들과의 통화. 전화가 울리면 반드시 받을 것",
      popularity: 1243.358,
      poster_path: "/eJPIkRiYGnvQaPCZtTRTDmhMJVK.jpg",
      release_date: "2022-06-22",
      title: "블랙폰",
      video: false,
      vote_average: 7.9,
      vote_count: 2531,
    },
    {
      adult: false,
      backdrop_path: "/xVbppM1xgbskOKgOuV8fbWBWHtt.jpg",
      genre_ids: [27, 9648, 878, 53],
      id: 762504,
      original_language: "en",
      original_title: "Nope",
      overview:
        "거대하고, 주목받길 원하고, 미쳤다. 나쁜 기적이라는 것도 있을까?",
      popularity: 1147.904,
      poster_path: "/52McjY2vAEiF0lJe8iBdOBNuyok.jpg",
      release_date: "2022-07-20",
      title: "놉",
      video: false,
      vote_average: 7,
      vote_count: 1507,
    },
    {
      adult: false,
      backdrop_path: "/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
      genre_ids: [28, 12, 878],
      id: 634649,
      original_language: "en",
      original_title: "Spider-Man: No Way Home",
      overview:
        "미스테리오의 계략으로 세상에 정체가 탄로난 스파이더맨 피터 파커는 하루 아침에 평범한 일상을 잃게 된다. 문제를 해결하기 위해 닥터 스트레인지를 찾아가 도움을 청하지만 뜻하지 않게 멀티버스가 열리면서 각기 다른 차원의 불청객들이 나타난다. 닥터 옥토퍼스를 비롯해 스파이더맨에게 깊은 원한을 가진 숙적들의 강력한 공격에 피터 파커는 사상 최악의 위기를 맞게 되는데…",
      popularity: 1098.544,
      poster_path: "/voddFVdjUoAtfoZZp2RUmuZILDI.jpg",
      release_date: "2021-12-15",
      title: "스파이더맨: 노 웨이 홈",
      video: false,
      vote_average: 8,
      vote_count: 15158,
    },
    {
      adult: false,
      backdrop_path: "/3VQj6m0I6gkuRaljmhNZl0XR3by.jpg",
      genre_ids: [16, 12, 35, 14],
      id: 585511,
      original_language: "en",
      original_title: "Luck",
      overview:
        "불운의 아이콘 '샘 그린필드'는 어디에서도 본 적 없는 운의 왕국을 우연히 발견하고, 가장 친한 친구에게 행운을 가져다주기 위해 그곳으로의 여행을 계획한다. 하지만 운의 왕국은 인간의 접근을 허락하지 않고, '샘 그린필드'는 여행을 실행에 옮기기 위한 유일한 방법으로 마법의 생명체들로부터 도움을 받게 된다.",
      popularity: 1006.391,
      poster_path: "/nN2iHej7TyISjXC6Jl577aqpDHJ.jpg",
      release_date: "2022-08-05",
      title: "럭",
      video: false,
      vote_average: 8,
      vote_count: 714,
    },
    {
      adult: false,
      backdrop_path: "/8wwXPG22aNMpPGuXnfm3galoxbI.jpg",
      genre_ids: [28, 12, 10751, 35],
      id: 675353,
      original_language: "en",
      original_title: "Sonic the Hedgehog 2",
      overview:
        "강력한 파워의 ‘너클즈’와 함께 돌아온 천재 과학자 ‘닥터 로보트닉’에 맞서 지구를 구하기 위해 ‘소닉’과 새로운 파트너 ‘테일즈’가 전 세계를 누비는 스피드 액션 블록버스터.",
      popularity: 913.777,
      poster_path: "/arCDDZdvamNY628gWJVjlCycf69.jpg",
      release_date: "2022-03-30",
      title: "수퍼 소닉 2",
      video: false,
      vote_average: 7.7,
      vote_count: 3012,
    },
    {
      adult: false,
      backdrop_path: "/rwgmDkIEv8VjAsWx25ottJrFvpO.jpg",
      genre_ids: [10749, 18],
      id: 744276,
      original_language: "en",
      original_title: "After Ever Happy",
      overview:
        "뉴욕으로 떠난 테사와 소설가로 데뷔한 하딘,  런던에서 삶을 송두리째 뒤흔들 엄청난 과거를 알게 된 하딘은 자신의 불행 속에 테사를 끌어들이기 싫어서 애써 밀어낸다.  계속 제자리만 맴도는 관계에 지친 테사는 새로운 삶을 꿈꾸며 뉴욕으로 향하고, 떨어진 동안 그의 소중함을 깨달은 하딘은 뉴욕에서 테사와 재회하여 서로의 숨결과 살결을 탐한다.  다시 미래를 꿈꾸던 테사는 하딘이 집필한 소설 ‘애프터’에 자신의 첫 키스부터 첫 경험뿐만 아니라 감추고 싶던 아픈 기억까지 모두 담겨 있다는 것을 알고 충격을 받는데…",
      popularity: 913.358,
      poster_path: "/fZqvzsekRXxRrtEKIWoAWP5eqe7.jpg",
      release_date: "2022-08-24",
      title: "애프터: 에버 해피",
      video: false,
      vote_average: 6.4,
      vote_count: 65,
    },
    {
      adult: false,
      backdrop_path: "/qViFGWCHaSmW4gP00RGh3xjMjsP.jpg",
      genre_ids: [27, 9648],
      id: 758724,
      original_language: "en",
      original_title: "The Cellar",
      overview:
        "키이라 우즈의 딸은 그들의 새로운 집 지하실에서 불가사의하게 사라진다.\r 그녀는 곧 그녀의 가족들이 영원히 영혼을 잃을 위험에 직면해있고,  그들의 집을 통제하는 강력하고 오래된 무언가가 있다는 것을 알게 된다.",
      popularity: 754.557,
      poster_path: "/rtfGeS5WMXA6PtikIYUmYTSbVdg.jpg",
      release_date: "2022-03-25",
      title: "더 셀러",
      video: false,
      vote_average: 6.6,
      vote_count: 236,
    },
    {
      adult: false,
      backdrop_path: "/r26Qj2HfAv6rPXzULLpdDWrkwrT.jpg",
      genre_ids: [53],
      id: 852448,
      original_language: "en",
      original_title: "I Came By",
      overview:
        "부유층의 집을 표적으로 삼는 그라피티 아티스트가 숨겨져 있던 지하실에서 어두운 비밀을 발견한다. 그리고 이때부터 사랑하는 주변 사람들이 위험에 처하게 되는데.",
      popularity: 711.896,
      poster_path: "/3msHSRFGIenGYNCM0wevHfkyjsq.jpg",
      release_date: "2022-08-19",
      title: "아이 케임 바이",
      video: false,
      vote_average: 6.3,
      vote_count: 261,
    },
    {
      adult: false,
      backdrop_path: "/iGHFjqxH5c8zRibnZbh9qEYTBho.jpg",
      genre_ids: [28],
      id: 1008779,
      original_language: "es",
      original_title: "La Princesa",
      overview: "",
      popularity: 771.277,
      poster_path: "/ksxiXqwPuEjh3gct1zUpyzNoQFt.jpg",
      release_date: "2022-08-05",
      title: "La Princesa",
      video: false,
      vote_average: 7.5,
      vote_count: 60,
    },
    {
      adult: false,
      backdrop_path: "/fqw8nJLPRgKRyFSDC0xBsC06NGC.jpg",
      genre_ids: [28, 12, 14],
      id: 639933,
      original_language: "en",
      original_title: "The Northman",
      overview:
        "10세기 아이슬란드, 숙부를 향한 '암레트' 왕자의 복수극을 그린 영화",
      popularity: 582.764,
      poster_path: "/Aedz3vL7rC5fO0t7vQK7KUMwiW5.jpg",
      release_date: "2022-04-07",
      title: "노스맨",
      video: false,
      vote_average: 7.2,
      vote_count: 2376,
    },
    {
      adult: false,
      backdrop_path: "/ufagam4FwlIcgPqJlr21EshNkNd.jpg",
      genre_ids: [27, 53],
      id: 629015,
      original_language: "en",
      original_title: "Shut In",
      overview:
        "죽은 할머니의 오래된 집을 정리하고 떠나려던 '제시카' 앞에 불청객인 마약 중독자 전 남편과 그의 친구 ‘새미’가 들이닥친다. 마약에 취해 과격해 진 남편은 2평 남짓한 창고 안에 그녀를 가둬버리고 떠난 줄 알았던 범죄자 '새미'까지 다시 돌아와 그녀의 유일한 희망인 아이들을 위협하기 시작하는데…",
      popularity: 504.014,
      poster_path: "/8iYwyAv9PgCKdBQypx23o8LEjgm.jpg",
      release_date: "2022-03-24",
      title: "셧 인",
      video: false,
      vote_average: 7.1,
      vote_count: 213,
    },
    {
      adult: false,
      backdrop_path: "/pdD47rPAYKVdPasoyhSAFPIFIWo.jpg",
      genre_ids: [28, 35, 53],
      id: 718930,
      original_language: "en",
      original_title: "Bullet Train",
      overview:
        "운이 없기로 유명한 킬러 레이디버그는 초고속 열차에 탑승해 의문의 서류 가방을 가져오라는 미션을 받는다. 생각보다 쉽게 미션을 클리어한 후 열차에서 내리려는 그를 가로막는 것이 있었으니,  그것은 바로 전세계에서 몰려든 초특급 킬러들! 열차에서 내릴 수 없다면 목숨을 걸고 가방을 지켜야만 한다. 과연 레이디버그는 무사히 열차에서 내려 미션을 완수할 수 있을까?",
      popularity: 553.439,
      poster_path: "/msh4N8dxHk4FeEPZ8VBqHQFQYjI.jpg",
      release_date: "2022-07-03",
      title: "불릿 트레인",
      video: false,
      vote_average: 7.5,
      vote_count: 830,
    },
    {
      adult: false,
      backdrop_path: "/vjnLXptqdxnpNJer5fWgj2OIGhL.jpg",
      genre_ids: [28, 53, 80],
      id: 818397,
      original_language: "en",
      original_title: "Memory",
      overview:
        "단 한번의 실패도 실수도 용납할 수 없는 킬러 ‘알렉스’(리암 니슨). 어느 날, 그에게 새로운 의뢰가 들어온다.  오직 자신의 신념에 따라 움직인 그는 이 사건에 한 소녀가 연관되어 있음을 알게 되고 단칼에 거절한다.  의뢰를 거절했다는 이유로, 모두의 표적이 되어버린 그는 오래된 병으로 인해 희미해져 가는 기억을 붙잡고,  소녀와 자신을 지키기 위해 의뢰에 연관된 모든 것들을 응징하기로 한다.  한편, 멕시코 국경에서 사건을 맹렬히 쫓던 FBI 요원 ‘빈센트’(가이 피어스)는 ‘알렉스’를 만나게 되고, 두 사람은 이 사건의 거대한 비밀과 마주하게 되는데···  사라지는 기억, 더욱 선명해지는 정의! 마지막 응징이 시작된다!",
      popularity: 542.927,
      poster_path: "/fWkFnlCQLtfIBGnhMKVw2dttEDk.jpg",
      release_date: "2022-04-28",
      title: "메모리",
      video: false,
      vote_average: 7.2,
      vote_count: 788,
    },
  ],
  total_pages: 87,
  total_results: 1736,
};
